// <auto-generated />
namespace IBE.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class db3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db3));
        
        string IMigrationMetadata.Id
        {
            get { return "202305030808321_db3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
